name: zeine_dev_challenge

services:
  postgres:
    container_name: db
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zeine_dev_challenge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
